# This file can be used to test api endpoints
# to use you need to install REST CLient extension on VS Code

@port = 5000
@protocol = http
@hostname = localhost
@base_url = {{protocol}}://{{hostname}}:{{port}}

@email = root@example.com
@password = root

### Returns a security web token
POST {{base_url}}/api/auth
content-type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### List all students
GET {{base_url}}/api/students
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJyb290QGV4YW1wbGUuY29tIiwiaWF0IjoxNzM4MDQyMTUyLCJleHAiOjE3MzgwNDU3NTJ9.-Y8LjU2PDk-jZlaBNHzXrbCRDL21okUhK7zAso8jY3g

### Creates a new student 
POST {{base_url}}/api/students
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJyb290QGV4YW1wbGUuY29tIiwiaWF0IjoxNzM4MDQyMTUyLCJleHAiOjE3MzgwNDU3NTJ9.-Y8LjU2PDk-jZlaBNHzXrbCRDL21okUhK7zAso8jY3g

{
  "name": "Jonh Doe",
  "age": 18,
  "grade": "1A"
}

### Updated student data
DELETE {{base_url}}/api/students/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJyb290QGV4YW1wbGUuY29tIiwiaWF0IjoxNzM4MDQyMTUyLCJleHAiOjE3MzgwNDU3NTJ9.-Y8LjU2PDk-jZlaBNHzXrbCRDL21okUhK7zAso8jY3g

